lesson12
atitorenko/tiny-event-sourcing-demo pull request #1
Opened 2023-03-14 18:32 UTC by atitorenko

+ Классы-состояния агрегатов
+ События агрегатов
+ Команды агрегатов
+ Функции для транзита состояний.
+ rest api

2023-03-19 20:13 UTC, sevabeat requested changes
Команды/События/Функции перехода сделаны верно
Есть замечания (В основном связанные с валидациями)

2023-03-19 20:13 UTC, sevabeat commented on README.md
> +To ru.quipy.logic.commands.create new Project with name "Project" and creator user "Andrey" call:
Зачем тут ru.quipy.logic.commands.create?

2023-03-19 20:13 UTC, sevabeat commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +        val projectCreatedState = projectEsService.create { it.create(UUID.randomUUID(), projectName, creatorId) }
имя переменной "projectCreatedState" вводит в заблуждение, тк в ней хранится не state, а event

2023-03-19 20:13 UTC, sevabeat commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +        createTaskStatus(
Здесь нет необходимости делать создание проекта и добавление в него стандартных статусов в две операции. Создание стандартных статусов должно происходить в команде project.create

2023-03-19 20:13 UTC, sevabeat commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +    fun getProject(projectId: UUID): ProjectAggregateState? {
В данном задании нужно было реализовать только команды. Query мы будем делать используя шаблон CQRS (будет в следующих занятиях). Получение последнего состояния агрегата нужно только для исполнения команд. Любые запросы должны идти к проекциям (это все будет в лекциях про CQRS)

Но пока этот код можно оставить.

2023-03-19 20:13 UTC, sevabeat commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +        if (getProjectInternal(projectId).projectName == newName) return null
Эту валидацию можно и нужно вынести в команду updateProjectName. Нет необходимости получать актуальное состояние агрегата здесь, это и так делается в projectEsService.update (состояние агрегата передается параметром в лямбду)

2023-03-19 20:13 UTC, sevabeat commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +        if (projectState.creatorId == userId) throw TaskProjectException("Creator can't leave his project")
тоже самое, валидацию нужно вынести в команду

2023-03-19 20:13 UTC, sevabeat commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +        if (projectState.participants.contains(userId)) return null;
тоже самое, валидацию нужно вынести в команду

2023-03-19 20:13 UTC, sevabeat commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +        if (projectState.taskStatuses.keys.containsAll(newOrderStatuses.orderedStatuses)) {
Можно легко улучшить читаемость кода, переписав это условие на if(!projectState.taskStatuses.keys.containsAll(...)) throw Exception()

2023-03-19 20:13 UTC, sevabeat commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +        if (projectState.taskStatuses.keys.containsAll(newOrderStatuses.orderedStatuses)) {
тоже самое, валидацию нужно вынести в команду

2023-03-23 15:54 UTC, atitorenko commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +        createTaskStatus(
надо записать параметры дефолтного статуса в евент и в транзишн функции создания добавить дефолтный статус?

2023-03-23 16:11 UTC, atitorenko commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +        if (projectState.creatorId == userId) throw TaskProjectException("Creator can't leave his project")
> тоже самое, валидацию нужно вынести в команду

проверку существования пользователя оставить в сервисе этом?

2023-03-25 00:51 UTC, sevabeat commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +        createTaskStatus(
Да

2023-03-25 00:51 UTC, sevabeat commented on src/main/kotlin/ru/quipy/logic/service/ProjectService.kt
> +        if (projectState.creatorId == userId) throw TaskProjectException("Creator can't leave his project")
Да

2023-03-25 00:52 UTC, sevabeat commented
Задание принято, можете смерджить пулл реквест

2023-03-25 10:15 UTC, merged